#!/bin/bash

#Color Code List

def="\e[1;"
red="${def}91m"
cyan="${def}96m"
yellow="${def}93m"
green="${def}92m"
reset="${def}0m"
blink="${def}5m"
ul="${def}4m"

alert=$green"[$red!$green]"
success=$red"[$green+$red]"
fail=$"$green[$red-$green]"

# Root check

if [ "$EUID" -ne 0 ]; then

echo -e "${alert} ${red}You shall not pass!\n"

fi


#Author name 

author="${red}ERROR 404"
yt="${yellow}https://www.youtube.com/channel/UCXM0-_7XMQKWpxuPBEo-VtQ?"

#Other modules

lip=`hostname -I`
pubip=`wget -qO- ifconfig.me/ip`
unamestr=`uname`

